### ISSUE TITLE
InfoButton Bileseni

### ISSUE THREAD

**Issue by mksglu** [Deipnon/deipnon#47]
## Açıklama

`Websitesi`nde bir restoranin bilgilerine ulasmak istedigimizde tiklamak icin kullanacagimiz `Info` butonu.

![image](https://user-images.githubusercontent.com/6067714/67284310-0f697f80-f4de-11e9-9f97-d31a0e0443b4.png)

## Kabul

Tek bir prop almasi yeterli.

`propName` - `Default`

onClick (null)

## Diğer

ikonu `react-icons` kutuphanesinden kullanabilirsiz.

**Comment by hadeyici** [comment]
https://github.com/Deipnon/deipnon/tree/infoButton @mksglu müsait olduğunda kontrol edebilir misin. Sonrasında PR açayım.
